# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: sigmoid-ThinkPad-T450
  

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    az login -u sachinshadadi@gmail.com -p SAChin@123
  displayName: 'login'


